name: Trigger auto deployment for testcontainerapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/testcontainerapp-AutoDeployTrigger-7ab80421-4fc1-4dc2-bbce-16159aba0a3b.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: jurinazurecontainerregistry.azurecr.io
          username: ${{ secrets.TESTCONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.TESTCONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jurinazurecontainerregistry.azurecr.io/testcontainerapp:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TESTCONTAINERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n testcontainerapp -g Default --server jurinazurecontainerregistry.azurecr.io --username  ${{ secrets.TESTCONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.TESTCONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n testcontainerapp -g Default --image jurinazurecontainerregistry.azurecr.io/testcontainerapp:${{ github.sha }}
